=== mojianyou/xq_mobile/src/com/wzljl/dtd/vote_cluster.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ATTLIST vote_cluster cid ID #REQUIRED>
<!ELEMENT vote_cluster (ctopic,cdescription,caddtime,vote_items) >
<!ELEMENT ctopic (#PCDATA) >
<!ELEMENT cdescription (#PCDATA) >
<!ELEMENT caddtime (#PCDATA) >
<!ELEMENT vote_items (vote_item+) >
<!ATTLIST vote_item iid ID #REQUIRED>
<!ELEMENT vote_item (itopic,banner,idescription,widget_style,max_opt,min_opt,beign_time,end_time,vail_style) >
<!ELEMENT itopic (#PCDATA) >
<!ELEMENT banner (#PCDATA) >
<!ELEMENT idescription (#PCDATA) >
<!ELEMENT widget_style (#PCDATA) >
<!ELEMENT max_opt (#PCDATA) >
<!ELEMENT min_opt (#PCDATA) >
<!ELEMENT beign_time (#PCDATA) >
<!ELEMENT end_time (#PCDATA) >
<!ELEMENT vail_style (#PCDATA) >

=== mojianyou/xq_mobile/src/com/wzljl/dtd/vote_cluster.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vote_cluster SYSTEM "vote_cluster.dtd" >
<vote_cluster cid="c1">
  <ctopic>小区投票</ctopic>
  <cdescription>投票系统</cdescription>
  <caddtime>2016-11-18</caddtime>
  <vote_items>
     <vote_item iid="i1">
        <itopic>美德投票</itopic>
        <banner>file.jpg</banner>
        <idescription>文明公益</idescription>
        <widget_style>s</widget_style>
        <max_opt>10</max_opt>
        <min_opt>1</min_opt>
        <beign_time>2016-11-19</beign_time>
        <end_time>2016-11-30</end_time>
        <vail_style>d</vail_style>
     </vote_item>
     <vote_item iid="i2">
        <itopic>环境投票</itopic>
        <banner>fil1e.jpg</banner>
        <idescription>文明学徒</idescription>
        <widget_style>s</widget_style>
        <max_opt>10</max_opt>
        <min_opt>1</min_opt>
        <beign_time>2016-11-19</beign_time>
        <end_time>2016-11-30</end_time>
        <vail_style>d</vail_style>
     </vote_item>
  </vote_items>
</vote_cluster>
